### PR TITLE
fix var_export of namespace names

### PR DESCRIPTION
**Pull request by eric-therond**

### CODE REVIEW

**Comment by nikic** [comment]
Not sure I understand the motivation for this change. Currently it's printed in a way that makes the literal a valid string. In these particular examples it happens to not be strictly necessary, but it would be if the string were `'\\'` for example.

**Comment by eric-therond** [comment]
@nikic the problem I faced is that literal are printed with `var_export`, that keep escaped chars, [example](https://github.com/ircmaxell/php-cfg/blob/master/test/code/class.test):

```
    Stmt_Class
        name: LITERAL('NS\\NameOfClass')
        extends: LITERAL('X')
        implements[0]: LITERAL('NS\\Iface')
        stmts: Block#3
```

while function names are printed [without var_export](https://github.com/ircmaxell/php-cfg/blob/master/lib/PHPCfg/Printer/Text.php#L26):
```
Function NS\NameOfClass::doSomething(): mixed
Block#1
    Terminal_Echo
        expr: LITERAL('Hello World')
    Terminal_Return
```

so there is an inconsistency in the class names (`NS\NameOfClass` and `NS\\NameOfClass` on other side).

Maybe this solution is more correct?
change [line 25](https://github.com/ircmaxell/php-cfg/blob/master/lib/PHPCfg/Printer/Text.php#L25) to:
```
$name = var_export($func->getScopedName(), true);
```

**Comment by ircmaxell** [comment]
That second change seems more inline, it'll make the function name a string as well as escaping more consistently. +1 from me.

**Comment by eric-therond** [comment]
looking good now on your side @nikic @ircmaxell ?

**Pull request merged**
