### PR TITLE
support trait use

### PR DESCRIPTION
**Pull request by LioTree**
Hi,I add the feature to support trait use.

### CODE REVIEW

**Comment by ircmaxell** [comment]
Added a few comments inline. The structure of the overall layout of classes is one thing i'd love feedback on, as the current implementation feels a bit too ad-hoc...

**Review by ircmaxell — COMMENTED** [review]
A few action items here to discuss...

**Comment by LioTree** [comment]
I modified it according to your comment, the current structure is

* Op\Stmt\TraitUse
* Op\TraitUseAdaptation
* Op\TraitUseAdaptation\Alias
* Op\TraitUseAdaptation\Precedence

**Comment by ircmaxell** [comment]
Thanks!

**Pull request merged**
