### PR TITLE
Support of namespace stmt

### PR DESCRIPTION
**Pull request by eric-therond**
Sometimes we need to know in which location the namespace is inserted

### CODE REVIEW

**Comment by ircmaxell** [comment]
What's the use-case? As namespaces are all resolved as part of parsing, don't see the reason for bringing it forward as nodes (there's no behavior change, is there?)?

**Comment by eric-therond** [comment]
There is no behavior change
I need to know the precise location (file, line, ...) of the namepace stmt declarations in a project

**Comment by eric-therond** [comment]
Yes for sure, I can definitely use the AST
For now the CFG was my only source of information and it's convenient to have all the information in it
I will try directly with the AST

**Comment by ircmaxell** [comment]
I'll leave the PR open in case someone wants to make a case here (happy to be wrong or take a different perspective)

**Comment by eric-therond** [comment]
I was able to easily use the AST to have information about namespaces, through the use of `ASTtraverser`. But I believe the CFG should have this node too:
- today in the CFG we have, `class`, `interface` nodes for instance, and not `namespace`, why do we want to exclude this one and not other?
- in general, on the long term, I think the CFG should contain ALL the nodes, without any exclusions, I want to know about a specific node, `namespace` in this case, where it is in the CFG, in which block, in order to do some static analysis based on the location of nodes in the CFG.

**Comment by nikic** [comment]
I don't think that namespaces can be represented in the CFG in any simple way. Consider something like:
```
<?php

namespace A;

goto label;
label2:

namespace B;

label:
goto label2;
```

Control flow may freely leave an enter namespaces, it does not have to be strictly nested inside a namespace. If we wanted to represent this, it should probably rather be that a given block can be associated to a namespace.

**Comment by eric-therond** [comment]
To me, having information about blocks associated with namespaces seems like some sort of "semantic analysis" performed on top of the CFG (like identification of [loops](https://github.com/ircmaxell/php-cfg/pull/81#issuecomment-1060831108) from the CFG we discussed some weeks ago)?

I am maybe wrong but I don't see it as related to the first problem I wanted to solve, which is just having the namespace statement as node in the CFG:


```
<?php

namespace A;

funccallA();

namespace B;

funccallB();

-----
Block#1
    Stmt_Namespace
        name: LITERAL('A')
        stmts: Block#2

Block#2
    Expr_NsFuncCall
        nsName: LITERAL('A\\funccallA')
        name: LITERAL('funccallA')
        result: Var#1
    Stmt_Namespace
        name: LITERAL('B')
        stmts: Block#3

Block#3
    Expr_NsFuncCall
        nsName: LITERAL('B\\funccallB')
        name: LITERAL('funccallB')
        result: Var#2
    Terminal_Return
```

**Comment by ircmaxell** [comment]
Conceptually, it doesn't seem to make sense as a block itself. Control never enters a namespace node, hence why it feels weird having it as a block with a statement. Plus, it's a purely compile time construct, meaning that control flow doesn't affect it by definition, so representing it as an entity within a CFG feels off.

What I could see as useful here would be to set it as a property on the block, such that each block shares which namespace it was a part of:

```
<?php

namespace A;

funccallA();

namespace B;

funccallB();

-----
Block#1 <namespace: A>
    Expr_NsFuncCall
        nsName: LITERAL('A\\funccallA')
        name: LITERAL('funccallA')
        result: Var#1

Block#2 <namespace: B>
    Expr_NsFuncCall
        nsName: LITERAL('B\\funccallB')
        name: LITERAL('funccallB')
        result: Var#2
    Terminal_Return
 ```

**Pull request closed without merging**
